SET local check_function_bodies = off;

CREATE TABLE "public"."backup_instructor_options" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "backup_instructor_options_name_key" UNIQUE (name),
  CONSTRAINT "backup_instructor_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."backup_instructor_options"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."belt_options" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "belt_options_name_key" UNIQUE (name),
  CONSTRAINT "belt_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."belt_options"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."camp_options" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "camp_options_name_key" UNIQUE (name),
  CONSTRAINT "camp_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."camp_options"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."class_status_options" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."class_status_options_id_seq1") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "class_status_options_name_key1" UNIQUE (name),
  CONSTRAINT "class_status_options_pkey1" PRIMARY KEY (id)
);

ALTER TABLE "public"."class_status_options"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."end_time" (
  "id"   bigint              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" time with time zone NOT NULL,
  CONSTRAINT "end_time_name_key" UNIQUE (name),
  CONSTRAINT "end_time_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."end_time"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."hub_options" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."class_status_options_id_seq") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "class_status_options_name_key" UNIQUE (name),
  CONSTRAINT "class_status_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."hub_options"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."instructor_options" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "instructor_options_name_key" UNIQUE (name),
  CONSTRAINT "instructor_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."instructor_options"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."notes" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "notes_name_key" UNIQUE (name),
  CONSTRAINT "notes_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."notes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."start_time" (
  "id"   bigint              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" time with time zone NOT NULL,
  CONSTRAINT "start_time_name_key" UNIQUE (name),
  CONSTRAINT "start_time_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."start_time"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sub_option" (
  "id"  bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sub" boolean NOT NULL,
  CONSTRAINT "sub_option_pkey" PRIMARY KEY (id),
  CONSTRAINT "sub_option_sub_key" UNIQUE (sub)
);

ALTER TABLE "public"."sub_option"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."backup_instructor_options" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."belt_options" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."camp_options" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."class_status_options" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."end_time" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."hub_options" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."instructor_options" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."notes" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."start_time" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sub_option" TO "anon", "authenticated", "postgres", "service_role";

