DROP TABLE "public"."backup_instructor_options";

DROP TABLE "public"."belt_options";

DROP TABLE "public"."camp_options";

DROP TABLE "public"."class_status_options";

DROP TABLE "public"."end_time";

DROP TABLE "public"."hub_options";

DROP TABLE "public"."instructor_options";

DROP TABLE "public"."start_time";

DROP TABLE "public"."sub_option";

CREATE TABLE "public"."backUp" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."backup_instructor_options_id_seq") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "backup_instructor_options_name_key" UNIQUE (name),
  CONSTRAINT "backup_instructor_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."backUp"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."belt" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."belt_options_id_seq") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "belt_options_name_key" UNIQUE (name),
  CONSTRAINT "belt_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."belt"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."camp" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."camp_options_id_seq") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "camp_options_name_key" UNIQUE (name),
  CONSTRAINT "camp_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."camp"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."class" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."class_status_options_id_seq1") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "class_status_options_name_key1" UNIQUE (name),
  CONSTRAINT "class_status_options_pkey1" PRIMARY KEY (id)
);

ALTER TABLE "public"."class"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."endTime" (
  "id"   bigint              GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."end_time_id_seq") NOT NULL,
  "name" time with time zone NOT NULL,
  CONSTRAINT "end_time_name_key" UNIQUE (name),
  CONSTRAINT "end_time_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."endTime"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."hub" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."class_status_options_id_seq") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "class_status_options_name_key" UNIQUE (name),
  CONSTRAINT "class_status_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."hub"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."instructor" (
  "id"   bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."instructor_options_id_seq") NOT NULL,
  "name" text   NOT NULL,
  CONSTRAINT "instructor_options_name_key" UNIQUE (name),
  CONSTRAINT "instructor_options_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."instructor"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sessions" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "instructor"     text                     NOT NULL,
  """backUp"""     text,
  """subChecked""" boolean                  DEFAULT false,
  "status"         text                     DEFAULT 'None'::text,
  "hub"            text                     DEFAULT 'None'::text,
  "belt"           text,
  "camp"           text,
  """startTime"""  time without time zone,
  """endTime"""    time without time zone,
  "created_at"     timestamp with time zone DEFAULT now(),
  "backup"         text,
  "sub"            boolean                  DEFAULT false,
  "start_time"     text,
  "notes"          text,
  CONSTRAINT "sessions_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sessions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."startTime" (
  "id"   bigint              GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."start_time_id_seq") NOT NULL,
  "name" time with time zone NOT NULL,
  CONSTRAINT "start_time_name_key" UNIQUE (name),
  CONSTRAINT "start_time_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."startTime"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sub" (
  "id"  bigint  GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."sub_option_id_seq") NOT NULL,
  "sub" boolean NOT NULL,
  CONSTRAINT "sub_option_pkey" PRIMARY KEY (id),
  CONSTRAINT "sub_option_sub_key" UNIQUE (sub)
);

ALTER TABLE "public"."sub"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read" ON "public"."backUp"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."belt"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."camp"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."class"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."endTime"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."hub"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."instructor"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."notes"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow inserting sessions" ON "public"."sessions"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (true);

CREATE POLICY "Allow public inserts" ON "public"."sessions"
  FOR INSERT
  TO "anon"
  WITH CHECK (true);

CREATE POLICY "Allow public read" ON "public"."startTime"
  FOR SELECT
  TO "anon"
  USING (true);

CREATE POLICY "Allow public read" ON "public"."sub"
  FOR SELECT
  TO "anon"
  USING (true);

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."backUp" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."belt" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."camp" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."class" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."endTime" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."hub" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."instructor" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sessions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."startTime" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sub" TO "anon", "authenticated", "postgres", "service_role";

